apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1      
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      hostname: frontend
      containers:
      - name: frontend
        image: jasonsinclair95/group-project:frontend
        ports:
        - containerPort: 4200