apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels: 
    app: reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - name: nginx
        image: jasonsinclair95/group-project:nginx
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: petclinic-service-nginx
spec:
  type: ClusterIP
  selector:
    app: reverseproxy
  ports:
  - protocol: TCP
    port: 80             #service running on port 8080
    targetPort: 80         # app/pod running on port 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels: 
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: jasonsinclair95/group-project:frontend
        ports:
        - containerPort: 4200

---

apiVersion: v1
kind: Service
metadata:
  name: petclinic-service-frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 4200             #service running on port 8080
    targetPort: 4200 

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels: 
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: jasonsinclair95/group-project:backend
        ports:
        - containerPort: 9966

---

apiVersion: v1
kind: Service
metadata:
  name: petclinic-service-backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 9966             #service running on port 8080
    targetPort:  9966